from agent.context_builder.capability_context import CapabilityContextBuilder
from agent.behavior.loader import load_soul
from agent.gateway.message_types import ContextPackage
from agent.gateway.session_manager import SessionState
from agent.rag.retriever import RagRetriever
from agent.router.router_schema import RouterDecision
from agent.conversation_state.state import normalize_conversation_state
from agent.memory.memory_reader import load_relevant_learning_hints
from agent.memory.memory_hint_consumer import apply_learning_hints_to_capabilities
from agent.memory.user_memory import load_relevant_user_memories


class ContextBuilder:
    def __init__(
        self,
        capability_context=None,
        rag_retriever=None,
        learning_memory_store=None,
    ) -> None:
        self.capability_context = capability_context or CapabilityContextBuilder()
        self.rag_retriever = rag_retriever or RagRetriever()
        self.learning_memory_store = learning_memory_store

    def build(
        self,
        user_message: str,
        decision: RouterDecision,
        session: SessionState,
    ) -> ContextPackage:
        recent_history = list(session.history)
        if recent_history:
            last_turn = recent_history[-1]
            if last_turn.role == "user" and last_turn.content == user_message:
                recent_history = recent_history[:-1]

        learning_hints = load_relevant_learning_hints(
            self.learning_memory_store,
            user_message=user_message,
        )
        user_memories = load_relevant_user_memories(
            self.learning_memory_store,
            user_message=user_message,
        )
        capabilities = self.capability_context.select(decision)
        capabilities = apply_learning_hints_to_capabilities(
            capabilities,
            learning_hints,
            capability_context=self.capability_context,
        )
        rag_snippets = []
        if decision.needs_rag or decision.route == "rag_lookup":
            rag_snippets = self.rag_retriever.retrieve(user_message)[:3]
        safety_rules = [
            "No screenshots, vision, desktop automation, terminal commands, or file writes in current phase.",
            "Ask for confirmation before medium or high risk actions.",
            "Only web_search, browser_search, open_app, macOS observation tools, fixed macOS window tools, and fixed macOS Spaces tools may be executed in the current phase.",
            "web_search may search the web and return structured results to the agent. browser_search may open absolute http or https URLs and perform browser-based navigation/search in the browser.",
            "window_native_tiling may only act on the frontmost window using a fixed native menu allowlist and cannot verify the final position visually.",
            "macOS observation tools may read app/window/permission state but must not click, type, move windows, change Spaces, or request permissions.",
            "macOS Spaces tools may only use fixed System Events shortcuts for Spaces/Mission Control; never run AppleScript generated by the model.",
            "Use RAG snippets only for knowledge-base questions.",
        ]
        instruction = self._task_instruction(decision)
        soul = load_soul()
        return ContextPackage(
            system_prompt=(
                "You are a local MVP agent. Answer clearly and briefly. "
                "Use only approved capabilities for the current phase. "
                "Only web_search, browser_search, open_app, macOS observation tools, fixed macOS window tools, and fixed macOS Spaces tools may be executed."
            ),
            user_message=user_message,
            router_decision=decision,
            recent_history=recent_history,
            session_state={
                "pending_clarification": session.pending_clarification,
                "pending_confirmation": session.pending_confirmation,
                "pending_workflow": session.pending_workflow,
                "previous_route": session.previous_route,
                "current_route": session.current_route,
                "conversation_state": normalize_conversation_state(session.conversation_state),
                "learning_hints": learning_hints,
                "user_memories": user_memories,
            },
            behavior={
                "soul_loaded": soul.loaded,
                "soul_source": soul.source_path,
                "soul_fallback_used": soul.fallback_used,
                "soul_error": soul.error,
            },
            selected_plugins=capabilities["plugins"],
            selected_skills=capabilities["skills"],
            selected_tools=capabilities["tools"],
            rag_snippets=rag_snippets,
            safety_rules=safety_rules,
            task_instruction=instruction,
        )

    def _task_instruction(self, decision: RouterDecision) -> str:
        if decision.route == "clarification":
            return "Ask one short clarification question."
        if decision.route == "memory_lookup":
            return "Use persistent session memory only; do not search the knowledge base."
        if decision.route == "rag_lookup":
            return (
                "Answer using only the provided RAG snippets. "
                "If no snippets are available, say the knowledge base has no sufficient information."
            )
        if decision.route == "safety_confirmation":
            return "Ask for confirmation without executing the action."
        if decision.route == "action_ready":
            return (
                "If the request is specific enough, prefer an available low-risk tool_call. "
                "Use open_app for app names. "
                "Use web_search when the user wants information/results to answer from the web. Use browser_search only for opening browser pages, known web destinations, YouTube/Google navigation, and direct http/https URLs. "
                "Use window_native_tiling for moving, centering, filling, or resizing the frontmost macOS window with fixed native menu actions. "
                "Choose a specific target only when the user clearly requested that destination or provided a direct URL. "
                "Use macOS observation tools for app/window/permission/app-list questions. "
                "Use macOS window tools only for the frontmost window and never claim visual verification unless it is explicitly confirmed. "
                "Use macOS Spaces tools for Spaces, Desktop, and Mission Control questions. "
                "Do not act as if a browser action happened unless a real tool_call succeeded. "
                "Do not ask for permission for low-risk approved tools. "
                "Only answer directly without a tool if the tool would not help."
            )
        return "Respond normally."
