from agent.context_builder.capability_context import CapabilityContextBuilder
from agent.gateway.message_types import ContextPackage
from agent.gateway.session_manager import SessionState
from agent.rag.retriever import RagRetriever
from agent.router.router_schema import RouterDecision


class ContextBuilder:
    def __init__(self, capability_context=None, rag_retriever=None) -> None:
        self.capability_context = capability_context or CapabilityContextBuilder()
        self.rag_retriever = rag_retriever or RagRetriever()

    def build(
        self,
        user_message: str,
        decision: RouterDecision,
        session: SessionState,
    ) -> ContextPackage:
        recent_history = list(session.history)
        if recent_history:
            last_turn = recent_history[-1]
            if last_turn.role == "user" and last_turn.content == user_message:
                recent_history = recent_history[:-1]

        capabilities = self.capability_context.select(decision)
        rag_snippets = []
        if decision.needs_rag or decision.route == "rag_lookup":
            rag_snippets = self.rag_retriever.retrieve(user_message)[:3]
        safety_rules = [
            "No screenshots, vision, desktop automation, terminal commands, or file writes in current phase.",
            "Ask for confirmation before medium or high risk actions.",
            "Only browser_search, open_app, macOS observation tools, fixed macOS window tools, and fixed macOS Spaces tools may be executed in the current phase.",
            "browser_search may open absolute http or https URLs and perform browser-based information searches.",
            "window_native_tiling may only act on the frontmost window using a fixed native menu allowlist and cannot verify the final position visually.",
            "macOS observation tools may read app/window/permission state but must not click, type, move windows, change Spaces, or request permissions.",
            "macOS Spaces tools may only use fixed System Events shortcuts for Spaces/Mission Control; never run AppleScript generated by the model.",
            "Use RAG snippets only for knowledge-base questions.",
        ]
        instruction = self._task_instruction(decision)
        return ContextPackage(
            system_prompt=(
                "You are a local MVP agent. Answer clearly and briefly. "
                "Use only approved capabilities for the current phase. "
                "Only browser_search, open_app, macOS observation tools, fixed macOS window tools, and fixed macOS Spaces tools may be executed."
            ),
            user_message=user_message,
            router_decision=decision,
            recent_history=recent_history,
            session_state={
                "pending_clarification": session.pending_clarification,
                "pending_confirmation": session.pending_confirmation,
                "previous_route": session.previous_route,
                "current_route": session.current_route,
            },
            selected_plugins=capabilities["plugins"],
            selected_skills=capabilities["skills"],
            selected_tools=capabilities["tools"],
            rag_snippets=rag_snippets,
            safety_rules=safety_rules,
            task_instruction=instruction,
        )

    def _task_instruction(self, decision: RouterDecision) -> str:
        if decision.route == "clarification":
            return "Ask one short clarification question."
        if decision.route == "memory_lookup":
            return "Use persistent session memory only; do not search the knowledge base."
        if decision.route == "rag_lookup":
            return (
                "Answer using only the provided RAG snippets. "
                "If no snippets are available, say the knowledge base has no sufficient information."
            )
        if decision.route == "safety_confirmation":
            return "Ask for confirmation without executing the action."
        if decision.route == "action_ready":
            return (
                "If the request is specific enough, prefer an available low-risk tool_call. "
                "Use open_app for app names. "
                "Use browser_search for browser-based navigation, information search, known web destinations, and direct http/https URLs. "
                "Use window_native_tiling for moving, centering, filling, or resizing the frontmost macOS window with fixed native menu actions. "
                "Choose a specific target only when the user clearly requested that destination or provided a direct URL. "
                "Use macOS observation tools for app/window/permission/app-list questions. "
                "Use macOS window tools only for the frontmost window and never claim visual verification unless it is explicitly confirmed. "
                "Use macOS Spaces tools for Spaces, Desktop, and Mission Control questions. "
                "Do not act as if a browser action happened unless a real tool_call succeeded. "
                "Do not ask for permission for low-risk approved tools. "
                "Only answer directly without a tool if the tool would not help."
            )
        return "Respond normally."
